eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
    
micorservice:
  greeting-sevice:
    endpoints:
      endpoint:
        url: http://GREETINGSERVICE/greeting-service/retrieve
  name-sevice:
    endpoints:
      endpoint:
        url: http://NAMESERVICE/name-service/myname


logging:
  file:
    name: elk.log
    path: ${HOME}/Desktop/New folder/projects/spring-cloud/logs
